import type { FC, ReactNode } from 'react'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Providers } from '@/contexts/Providers'
import { navbarLinks } from '@/data'
import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/Footer'
import '@/styles/reset.css'
import '@/styles/globals.css'


const geistSans = Geist({
	subsets: ['latin'],
	variable: '--font-geist-sans',
})

const geistMono = Geist_Mono({
	subsets: ['latin'],
	variable: '--font-geist-mono',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	readonly children: ReactNode
}

const RootLayout: FC<RootLayoutProps> = ({
	children,
}: Readonly<{
	children: ReactNode
}>) => (
	<html lang="en">
		<body className={ `${geistSans.variable} ${geistMono.variable}` }>
			<Providers>
				<a className="hidden" href="#content">
					Skip to main content
				</a>
				<Header links={ navbarLinks } />
				<main id="content">
					{ children }
				</main>
				<Footer>test</Footer>
			</Providers>
		</body>
	</html>
)

export default RootLayout
